
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/hp/Desktop/MinGW/cmake-3.27.7-windows-x86_64/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:18 (project)"
    message: |
      The system is: Windows - 10.0.22000 - AMD64
...
