# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = C:\Users\hp\Desktop\MinGW\cmake-3.27.7-windows-x86_64\bin\cmake.exe

# The command to remove a file.
RM = C:\Users\hp\Desktop\MinGW\cmake-3.27.7-windows-x86_64\bin\cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\sorting-visualizer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\sorting-visualizer\build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	C:\Users\hp\Desktop\MinGW\cmake-3.27.7-windows-x86_64\bin\cmake-gui.exe -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	C:\Users\hp\Desktop\MinGW\cmake-3.27.7-windows-x86_64\bin\cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\sorting-visualizer\build\CMakeFiles C:\sorting-visualizer\build\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\sorting-visualizer\build\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sorting-visualizer

# Build rule for target.
sorting-visualizer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 sorting-visualizer
.PHONY : sorting-visualizer

# fast build rule for target.
sorting-visualizer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sorting-visualizer.dir\build.make CMakeFiles/sorting-visualizer.dir/build
.PHONY : sorting-visualizer/fast

src/SortAlgorithms.obj: src/SortAlgorithms.cpp.obj
.PHONY : src/SortAlgorithms.obj

# target to build an object file
src/SortAlgorithms.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sorting-visualizer.dir\build.make CMakeFiles/sorting-visualizer.dir/src/SortAlgorithms.cpp.obj
.PHONY : src/SortAlgorithms.cpp.obj

src/SortAlgorithms.i: src/SortAlgorithms.cpp.i
.PHONY : src/SortAlgorithms.i

# target to preprocess a source file
src/SortAlgorithms.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sorting-visualizer.dir\build.make CMakeFiles/sorting-visualizer.dir/src/SortAlgorithms.cpp.i
.PHONY : src/SortAlgorithms.cpp.i

src/SortAlgorithms.s: src/SortAlgorithms.cpp.s
.PHONY : src/SortAlgorithms.s

# target to generate assembly for a file
src/SortAlgorithms.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sorting-visualizer.dir\build.make CMakeFiles/sorting-visualizer.dir/src/SortAlgorithms.cpp.s
.PHONY : src/SortAlgorithms.cpp.s

src/SortController.obj: src/SortController.cpp.obj
.PHONY : src/SortController.obj

# target to build an object file
src/SortController.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sorting-visualizer.dir\build.make CMakeFiles/sorting-visualizer.dir/src/SortController.cpp.obj
.PHONY : src/SortController.cpp.obj

src/SortController.i: src/SortController.cpp.i
.PHONY : src/SortController.i

# target to preprocess a source file
src/SortController.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sorting-visualizer.dir\build.make CMakeFiles/sorting-visualizer.dir/src/SortController.cpp.i
.PHONY : src/SortController.cpp.i

src/SortController.s: src/SortController.cpp.s
.PHONY : src/SortController.s

# target to generate assembly for a file
src/SortController.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sorting-visualizer.dir\build.make CMakeFiles/sorting-visualizer.dir/src/SortController.cpp.s
.PHONY : src/SortController.cpp.s

src/Sortable.obj: src/Sortable.cpp.obj
.PHONY : src/Sortable.obj

# target to build an object file
src/Sortable.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sorting-visualizer.dir\build.make CMakeFiles/sorting-visualizer.dir/src/Sortable.cpp.obj
.PHONY : src/Sortable.cpp.obj

src/Sortable.i: src/Sortable.cpp.i
.PHONY : src/Sortable.i

# target to preprocess a source file
src/Sortable.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sorting-visualizer.dir\build.make CMakeFiles/sorting-visualizer.dir/src/Sortable.cpp.i
.PHONY : src/Sortable.cpp.i

src/Sortable.s: src/Sortable.cpp.s
.PHONY : src/Sortable.s

# target to generate assembly for a file
src/Sortable.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sorting-visualizer.dir\build.make CMakeFiles/sorting-visualizer.dir/src/Sortable.cpp.s
.PHONY : src/Sortable.cpp.s

src/Utils.obj: src/Utils.cpp.obj
.PHONY : src/Utils.obj

# target to build an object file
src/Utils.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sorting-visualizer.dir\build.make CMakeFiles/sorting-visualizer.dir/src/Utils.cpp.obj
.PHONY : src/Utils.cpp.obj

src/Utils.i: src/Utils.cpp.i
.PHONY : src/Utils.i

# target to preprocess a source file
src/Utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sorting-visualizer.dir\build.make CMakeFiles/sorting-visualizer.dir/src/Utils.cpp.i
.PHONY : src/Utils.cpp.i

src/Utils.s: src/Utils.cpp.s
.PHONY : src/Utils.s

# target to generate assembly for a file
src/Utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sorting-visualizer.dir\build.make CMakeFiles/sorting-visualizer.dir/src/Utils.cpp.s
.PHONY : src/Utils.cpp.s

src/main.obj: src/main.cpp.obj
.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sorting-visualizer.dir\build.make CMakeFiles/sorting-visualizer.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sorting-visualizer.dir\build.make CMakeFiles/sorting-visualizer.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sorting-visualizer.dir\build.make CMakeFiles/sorting-visualizer.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... sorting-visualizer
	@echo ... src/SortAlgorithms.obj
	@echo ... src/SortAlgorithms.i
	@echo ... src/SortAlgorithms.s
	@echo ... src/SortController.obj
	@echo ... src/SortController.i
	@echo ... src/SortController.s
	@echo ... src/Sortable.obj
	@echo ... src/Sortable.i
	@echo ... src/Sortable.s
	@echo ... src/Utils.obj
	@echo ... src/Utils.i
	@echo ... src/Utils.s
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

